#!/bin/bash

. /usr/sbin/so-common

# If this is changed, you MUST manually update local.bro to the desired path
OTX_PATH="/opt/bro/share/bro/policy/bro-otx"

# Download connector
echo
echo "Downloading Bro/OTX Connector ..."
echo
if [ ! -d $OTX_PATH ]; then
	git clone https://github.com/hosom/bro-otx $OTX_PATH
else
	echo "Bro-OTX directory already exists!"
fi
cd $OTX_PATH
if [ -d scripts ]; then
	cp -av scripts/* .
	rm -rf scripts
fi 

# Get APIKEY
echo
echo "Please provide an Alienvault OTX API key! [ENTER]:"
echo "(Input field is hidden)"
echo
read -s APIKEY

# Configure connector
echo "Configuring Bro OTX Connector..."
echo
if [ -f $OTX_PATH/bro-otx.conf ]; then
	sed -i "s|api_key.*|api_key = $APIKEY|" $OTX_PATH/bro-otx.conf
	sed -i "s|outfile.*|outfile = $OTX_PATH/otx.dat|" $OTX_PATH/bro-otx.conf
fi 
if [ -f $OTX_PATH/bro-otx.py ];then
	sed -i "s|default='bro-otx.conf'|default='$OTX_PATH/bro-otx.conf'|" $OTX_PATH/bro-otx.py
fi
 
# Add to local.bro
if [[ ! `grep bro-otx /opt/bro/share/bro/site/local.bro` ]] ; then
        cp /opt/bro/share/bro/site/local.bro /opt/bro/share/bro/site/local.bro.bak
        cat << EOF >> /opt/bro/share/bro/site/local.bro

# Load Bro OTX Pulses
@load bro-otx
EOF

else
        echo "@load bro-otx already exists in local.bro!"
fi
 
# Run Pulse retrieval script for first time
echo "Pulling OTX Pulses..."
echo
if [ -f $OTX_PATH/bro-otx.py ];then
	/usr/bin/python $OTX_PATH/bro-otx.py
fi

# Add cron job
echo "Adding cron job...will run hourly to pull new pulses"
echo
cat << EOF > /etc/cron.d/bro-otx
# /etc/cron.d/bro-otx
#
# crontab entry to manage Bro OTX pulse updates
 
SHELL=/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
 
0 * * * * root python $OTX_PATH/bro-otx.py >> /var/log/nsm/bro-otx.log 2>&1
EOF

# Restart Bro 
echo "Restarting Bro..."
echo
sudo nsm_sensor_ps-restart --only-bro
echo "Done!"
echo

# Check if script(s) loaded
if [[ `grep otx /nsm/bro/logs/current/loaded_scripts.log` ]]; then
	echo "Script(s) loaded!"
	echo
else
	echo "There seems to be an issue with your configuration.  Check /nsm/bro/logs/current/reporter.log for clues."
	echo
fi
